/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.1.0-dev (node-sequelize6 dev) on 2020-07-19 18:18:14.
 * Goto
 * https://github.com/mysql-workbench-schema-exporter/mysql-workbench-schema-exporter
 * for more information.
 */

const { DataTypes, Model } = require('sequelize');

class GwLog extends Model {
}

module.exports = (sequelize) => {
    return GwLog.init({
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        hash: {
            type: DataTypes.STRING(40)
        },
        imsi: {
            type: DataTypes.STRING(20)
        },
        type: {
            type: DataTypes.SMALLINT
        },
        address: {
            type: DataTypes.STRING(20)
        },
        data: {
            type: DataTypes.STRING(1024)
        },
        status: {
            type: DataTypes.SMALLINT
        },
        code: {
            type: DataTypes.SMALLINT
        },
        sent: {
            type: DataTypes.DATE
        },
        received: {
            type: DataTypes.DATE
        },
        time: {
            type: DataTypes.DATE
        }
    }, {
        sequelize: sequelize,
        modelName: 'GwLog',
        tableName: 'gw_log',
        indexes: [
            {
                name: 'hash',
                fields: ['hash']
            },
            {
                name: 'imsi',
                fields: ['imsi']
            },
            {
                name: 'type',
                fields: ['type']
            },
            {
                name: 'status',
                fields: ['status']
            }
        ],
        timestamps: false,
        underscored: true,
        syncOnAssociation: false
    });
}